services:
  - type: web
    name: telegram-lottery-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: "8444084929:AAEIkrCAeuNjSHVUCYE9AEpg6IFqE52rNxc"
    healthCheckPath: /health
